name: Docker CI with Maven

on:
  push:
  pull_request:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 22
          architecture: x64
          cache: maven

      - name: Maven Validate
        run: mvn -B --settings .mvn/custom-settings.xml validate
      - name: Maven Compile
        run: mvn -B --settings .mvn/custom-settings.xml compile

      - name: Maven Test
        run: mvn -B --settings .mvn/custom-settings.xml test -Pcoverage --fail-at-end
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            target/site/jacoco/jacoco.xml,
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

      - name: Maven Package
        run: mvn -B --settings .mvn/custom-settings.xml package
      - name: Maven Verify
        run: mvn -B --settings .mvn/custom-settings.xml verify

      - uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/mediatoad-1-SNAPSHOT-jar-with-dependencies.jar

  build-image:

    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
      
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: jar-file

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set env
        run: echo "DATE=$(date +%s)" >> $GITHUB_ENV

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
